"use client";

import { CheckCircle2, Loader2 } from "lucide-react";
import { useEffect, useState } from "react";
import { Alert, AlertDescription } from "./ui/alert";
import { Card } from "./ui/card";
import { Progress } from "./ui/progress";

const STEPS = [
  { id: "contextualize", label: "AI translating and contextualizing..." },
  { id: "generate", label: "Generating new PDF in browser..." },
];

export default function PDFProcessingView({ onComplete }) {
  const [currentStep, setCurrentStep] = useState(0);
  const [progress, setProgress] = useState(0);
  const [error, setError] = useState("");

  useEffect(() => {
    loadJsPDF();
  }, []);

  const loadJsPDF = () => {
    const script = document.createElement("script");
    script.src =
      "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js";
    script.onload = () => {
      console.log("✅ jsPDF loaded");
      processPDF();
    };
    document.body.appendChild(script);
  };

  const processPDF = async () => {
    try {
      const text = sessionStorage.getItem("pdfText");
      const fileName = sessionStorage.getItem("pdfFileName");
      const language = sessionStorage.getItem("targetLanguage");
      const region = sessionStorage.getItem("region");

      setCurrentStep(0);
      setProgress(20);

      const contextRes = await fetch("/api/contextualize-pdf", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text, targetLanguage: language, region }),
      });

      if (!contextRes.ok) throw new Error("Failed to contextualize");
      const { contextualizedText, changes } = await contextRes.json();

      setProgress(70);
      setCurrentStep(1);

      // Generate PDF in browser using jsPDF
      const { jsPDF } = window.jspdf;
      const doc = new jsPDF();

      // Add title
      doc.setFontSize(16);
      doc.text("Contextualized Document", 105, 20, { align: "center" });

      doc.setFontSize(10);
      doc.text("Generated by ContextAI", 105, 30, { align: "center" });

      // Add content (handle text wrapping)
      doc.setFontSize(11);
      const lines = doc.splitTextToSize(contextualizedText, 170);
      doc.text(lines, 20, 45);

      // Get PDF as base64
      const pdfBase64 = doc.output("datauristring").split(",")[1];

      setProgress(100);

      setTimeout(() => {
        onComplete({
          originalText: text,
          contextualizedText,
          pdfBase64,
          fileName: fileName.replace(".pdf", `_${language}.pdf`),
          language,
          region,
          changes,
        });
      }, 500);
    } catch (err) {
      console.error("Error:", err);
      setError(err.message);
    }
  };

  return (
    <div className="max-w-2xl mx-auto mt-12">
      <Card className="p-8">
        <h2 className="text-2xl font-bold text-center mb-8">Processing PDF</h2>
        {error ? (
          <Alert variant="destructive">
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        ) : (
          <>
            <Progress value={progress} className="mb-8" />
            <div className="space-y-4">
              {STEPS.map((step, i) => (
                <div
                  key={step.id}
                  className={`flex items-center gap-3 p-3 rounded-lg ${
                    i < currentStep
                      ? "bg-green-50"
                      : i === currentStep
                      ? "bg-blue-50"
                      : "bg-gray-50"
                  }`}
                >
                  {i < currentStep ? (
                    <CheckCircle2 className="w-5 h-5 text-green-600" />
                  ) : i === currentStep ? (
                    <Loader2 className="w-5 h-5 animate-spin text-blue-600" />
                  ) : (
                    <div className="w-5 h-5 rounded-full border-2 border-gray-300" />
                  )}
                  <span
                    className={
                      i <= currentStep ? "font-medium" : "text-gray-500"
                    }
                  >
                    {step.label}
                  </span>
                </div>
              ))}
            </div>
          </>
        )}
      </Card>
    </div>
  );
}
