"use client";

import { Copy, Download, FileText, Printer } from "lucide-react";
import { useState } from "react";
import { Badge } from "./ui/badge";
import { Button } from "./ui/button";
import { Card } from "./ui/card";

const LANGUAGE_NAMES = {
  hi: "Hindi",
  ta: "Tamil",
  te: "Telugu",
  kn: "Kannada",
  ml: "Malayalam",
  bn: "Bengali",
  mr: "Marathi",
  gu: "Gujarati",
};

export default function PDFViewer({ pdfData }) {
  const [copied, setCopied] = useState(false);

  const handleDownloadHTML = () => {
    const htmlContent = `
<!DOCTYPE html>
<html lang="${pdfData.language}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contextualized Document</title>
    <style>
        body {
            font-family: 'Noto Sans', Arial, sans-serif;
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            line-height: 1.8;
            font-size: 14pt;
        }
        h1 {
            text-align: center;
            color: #333;
            margin-bottom: 10px;
        }
        .subtitle {
            text-align: center;
            color: #666;
            font-size: 12pt;
            margin-bottom: 40px;
        }
        .content {
            text-align: justify;
            white-space: pre-wrap;
        }
        @media print {
            body { margin: 0; padding: 20px; }
        }
    </style>
</head>
<body>
    <h1>Contextualized Document</h1>
    <p class="subtitle">Generated by ContextAI</p>
    <div class="content">${pdfData.contextualizedText}</div>
</body>
</html>
    `;

    const blob = new Blob([htmlContent], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = pdfData.fileName.replace(/\.(pdf|txt)$/, ".html");
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadText = () => {
    const textContent = `Contextualized Document
Generated by ContextAI

${pdfData.contextualizedText}`;

    const blob = new Blob([textContent], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = pdfData.fileName;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    const printWindow = window.open("", "_blank");
    printWindow.document.write(`
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Print Document</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            line-height: 1.8;
            font-size: 12pt;
        }
        h1 { text-align: center; margin-bottom: 10px; }
        .subtitle { text-align: center; color: #666; margin-bottom: 40px; }
        .content { text-align: justify; white-space: pre-wrap; }
    </style>
</head>
<body>
    <h1>Contextualized Document</h1>
    <p class="subtitle">Generated by ContextAI</p>
    <div class="content">${pdfData.contextualizedText}</div>
</body>
</html>
    `);
    printWindow.document.close();
    setTimeout(() => {
      printWindow.print();
    }, 250);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(pdfData.contextualizedText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="max-w-5xl mx-auto">
      <Card className="p-6 mb-6 bg-gradient-to-r from-blue-50 to-purple-50">
        <div className="flex justify-between items-center flex-wrap gap-4">
          <div>
            <h3 className="text-lg font-bold mb-2">Document Ready! 🎉</h3>
            <div className="flex gap-2 flex-wrap">
              <Badge variant="secondary">
                {LANGUAGE_NAMES[pdfData.language]}
              </Badge>
              <Badge
                variant="outline"
                className="bg-green-50 text-green-700 border-green-300"
              >
                ✓ Indian Language Support
              </Badge>
            </div>
          </div>
          <div className="flex gap-2 flex-wrap">
            <Button
              onClick={handleDownloadHTML}
              size="lg"
              className="bg-gradient-to-r from-blue-600 to-purple-600"
            >
              <Download className="w-5 h-5 mr-2" />
              Download HTML
            </Button>
            <Button onClick={handleDownloadText} size="lg" variant="outline">
              <FileText className="w-5 h-5 mr-2" />
              Download Text
            </Button>
            <Button onClick={handlePrint} size="lg" variant="outline">
              <Printer className="w-5 h-5 mr-2" />
              Print as PDF
            </Button>
          </div>
        </div>
      </Card>

      <Card className="p-6 mb-6">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-lg font-semibold">Translated Content</h3>
          <Button onClick={handleCopy} variant="outline" size="sm">
            <Copy className="w-4 h-4 mr-2" />
            {copied ? "Copied!" : "Copy All"}
          </Button>
        </div>
        <div className="bg-gray-50 p-6 rounded-lg max-h-[600px] overflow-y-auto border-2 border-gray-200">
          <h2 className="text-xl font-bold text-center mb-2">
            Contextualized Document
          </h2>
          <p className="text-sm text-gray-600 text-center mb-6">
            Generated by ContextAI
          </p>
          <div className="prose max-w-none">
            <p className="whitespace-pre-wrap text-justify leading-relaxed text-base">
              {pdfData.contextualizedText}
            </p>
          </div>
        </div>
      </Card>

      <Card className="p-6 mb-6 bg-yellow-50 border-2 border-yellow-200">
        <h3 className="font-semibold text-lg mb-3 text-yellow-900">
          📄 How to Save as PDF:
        </h3>
        <ol className="space-y-2 text-sm text-yellow-900">
          <li>
            <strong>Option 1:</strong> Click "Print as PDF" button above →
            Choose "Save as PDF" in print dialog
          </li>
          <li>
            <strong>Option 2:</strong> Download HTML → Open in browser → Press
            Ctrl+P → Save as PDF
          </li>
          <li>
            <strong>Option 3:</strong> Copy text → Paste in Google Docs/Word →
            Export as PDF
          </li>
        </ol>
      </Card>

      {pdfData.changes.examples && pdfData.changes.examples.length > 0 && (
        <Card className="p-6">
          <h3 className="font-semibold text-lg mb-4">
            Cultural Adaptations Made:
          </h3>
          <ul className="space-y-2">
            {pdfData.changes.examples.map((ex, i) => (
              <li key={i} className="flex gap-2 text-sm">
                <span className="text-green-600">✓</span>
                <span>{ex}</span>
              </li>
            ))}
          </ul>
        </Card>
      )}
    </div>
  );
}
